FROM postgres

USER postgres
WORKDIR /app

COPY modules/repositoryJdbi/src/sql/create-schema.sql /docker-entrypoint-initdb.d/1_create.sql

COPY --chown=postgres:postgres modules/host/tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432
